apiVersion: v1
kind: Service
metadata:
  name: sample-model-service
  namespace: ai-models
spec:
  selector:
    app: sample-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
